//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.25 at 06:50:50 PM BST 
//


package uk.ac.surrey.ee.iot.fiware.ngsi9.pojo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContextElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContextElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="entityId" type="{}EntityId"/>
 *         &lt;element name="attributeDomainName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="contextAttributeList" type="{}ContextAttributeList" minOccurs="0"/>
 *         &lt;element name="domainMetadata" type="{}ContextMetadataList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContextElement")
public class ContextElement {

    @XmlElement(required = true)
    protected EntityId entityId;
    protected String attributeDomainName;
    protected ContextAttributeList contextAttributeList;
    protected ContextMetadataList domainMetadata;

    /**
     * Gets the value of the entityId property.
     * 
     * @return
     *     possible object is
     *     {@link EntityId }
     *     
     */
    public EntityId getEntityId() {
        return entityId;
    }

    /**
     * Sets the value of the entityId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityId }
     *     
     */
    public void setEntityId(EntityId value) {
        this.entityId = value;
    }

    /**
     * Gets the value of the attributeDomainName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeDomainName() {
        return attributeDomainName;
    }

    /**
     * Sets the value of the attributeDomainName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeDomainName(String value) {
        this.attributeDomainName = value;
    }

    /**
     * Gets the value of the contextAttributeList property.
     * 
     * @return
     *     possible object is
     *     {@link ContextAttributeList }
     *     
     */
    public ContextAttributeList getContextAttributeList() {
        return contextAttributeList;
    }

    /**
     * Sets the value of the contextAttributeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextAttributeList }
     *     
     */
    public void setContextAttributeList(ContextAttributeList value) {
        this.contextAttributeList = value;
    }

    /**
     * Gets the value of the domainMetadata property.
     * 
     * @return
     *     possible object is
     *     {@link ContextMetadataList }
     *     
     */
    public ContextMetadataList getDomainMetadata() {
        return domainMetadata;
    }

    /**
     * Sets the value of the domainMetadata property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextMetadataList }
     *     
     */
    public void setDomainMetadata(ContextMetadataList value) {
        this.domainMetadata = value;
    }

}
