//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 11:32:08 AM BST 
//
package uk.ac.surrey.ee.iot.fiware.ngsi9.pojo;

import java.util.List;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.JAXBIntrospector;
import javax.xml.bind.Unmarshaller;
import javax.xml.bind.annotation.*;
import org.w3c.dom.Node;

/**
 * <p>
 * Java class for ContextMetadata complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType name="ContextMetadata">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="value" type="{}Value"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContextMetadata")
@XmlRootElement(name = "contextMetadata")
//@XmlSeeAlso (value={ContextMetadataString.class,ContextMetadataObject.class})
public class ContextMetadata<T> {

    @XmlElement(name = "name", required = true)
    protected String name;
    @XmlElement(name = "type", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String type;
    @XmlElement(name="value", required = true)
//    protected Value value;
//    @XmlAnyElement//(lax = true)
    protected T value;

    public T getValue() {
        System.out.println("hi getValue");
//        try {
//            System.out.println("try getValue JAXBElement");
////            this.value = JAXBIntrospector.getValue(value);
//            System.out.println(this.value.getClass().getName());
//            JAXBContext context = JAXBContext.newInstance(Value.class);
//            JAXBElement<Value> element = (JAXBElement<Value>) context.createUnmarshaller().unmarshal((org.apache.xerces.dom.ElementNSImpl) (value));
//            this.value = JAXBIntrospector.getValue(element);
//            return element;
//        } catch (Exception e) {
//            System.out.println("Exception has been caught: " + e.getMessage());
//        }
        return value;
    }

    public void setValue(T value) {
//        System.out.println("hi setValue");
//        if (value instanceof JAXBElement) {
//            System.out.println("hi setValue JAXBElement");
//            this.value = JAXBIntrospector.getValue(value);
//        } else {
//            this.value = value;
//        }
        
         this.value = value;

    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

//    public Value getValue() {
//        return value;
//    }
//    public void setValue(Value value) {
//        this.value = value;
//    }
}
