//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.25 at 06:50:50 PM BST 
//
package uk.ac.surrey.ee.iot.fiware.ngsi9.pojo;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonRootName;
import java.util.ArrayList;
import java.util.List;

@JsonRootName("EntityId")
public class ContextRegistrationAttribute {

//    @XmlElement(required = true)
    protected String name;
    protected String type;
    protected boolean isDomain;
//    @XmlElementWrapper(name = "metadata")
    @JsonProperty("metadatas")
    protected List<ContextMetadata> contextMetadata;

    /**
     * Gets the value of the name property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the isDomain property.
     *
     */
    public boolean isIsDomain() {
        return isDomain;
    }

    /**
     * Sets the value of the isDomain property.
     *
     */
    public void setIsDomain(boolean value) {
        this.isDomain = value;
    }

    /**
     * Gets the value of the metadata property.
     *
     * @return possible object is {@link ContextMetadataList }
     *
     */
//    public ContextMetadataList getMetadata() {
//        return metadata;
//    }
    /**
     * Sets the value of the metadata property.
     *
     * @param value allowed object is {@link ContextMetadataList }
     *
     */
//    public void setMetadata(ContextMetadataList value) {
//        this.metadata = value;
//    }
    public List<ContextMetadata> getContextMetadata() {
        if (contextMetadata == null) {
            contextMetadata = new ArrayList<ContextMetadata>();
        }
        return this.contextMetadata;
    }

}
