//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 11:32:08 AM BST 
//
package uk.ac.surrey.ee.iot.fiware.ngsi9.pojo;

import com.fasterxml.jackson.annotation.JsonRootName;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import javax.xml.bind.annotation.*;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContextMetadata")
@XmlRootElement(name = "contextMetadata")
@JsonRootName ("contextMetadata")
//@XmlSeeAlso (value={ContextMetadataString.class,ContextMetadataObject.class})
public class ContextMetadataString extends ContextMetadata {

    @XmlElement(name = "name", required = true)
    protected String name;
    @XmlElement(name = "type", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String type;
    @XmlElement(name="value", required = true)
    protected String value;

    @Override
    public String getValue() {
        System.out.println("hi getValue");
        
        return value;
    }

    public void setValue(String value) {
        
         this.value = value;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String getType() {
        return type;
    }

    @Override
    public void setType(String type) {
        this.type = type;
    }
    
}
