//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.20 at 04:30:24 PM GMT 
//


package uk.ac.surrey.ee.iot.fiware.ngsi9.pojo;

import com.fasterxml.jackson.annotation.JsonProperty;

public class OperationScope {

    @JsonProperty("type")
    protected String scopeType;
    @JsonProperty("value")
    protected Object scopeValue;
    
    public OperationScope(){}
    
    public OperationScope(String scopeType, Object scopeValue){
    
        this.scopeType=scopeType;
        this.scopeValue=scopeValue;
    }

    /**
     * Gets the value of the scopeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScopeType() {
        return scopeType;
    }

    /**
     * Sets the value of the scopeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScopeType(String value) {
        this.scopeType = value;
    }

    /**
     * Gets the value of the scopeValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public Object getScopeValue() {
        return scopeValue;
    }

    /**
     * Sets the value of the scopeValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScopeValue(Object value) {
        this.scopeValue = value;
    }

}
