//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.25 at 06:50:50 PM BST 
//


package uk.ac.surrey.ee.iot.fiware.ngsi9.pojo;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;

public class Restriction {

    protected String attributeExpression;
    @JsonProperty("scopes")
    protected List<OperationScope> operationScope;

    /**
     * Gets the value of the attributeExpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeExpression() {
        return attributeExpression;
    }

    /**
     * Sets the value of the attributeExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeExpression(String value) {
        this.attributeExpression = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link OperationScopeList }
     *     
     */
    public List<OperationScope> getOperationScope() {
        if (operationScope == null) {
            operationScope = new ArrayList<>();
        }
        return this.operationScope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationScopeList }
     *     
     */
    

}
