//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.25 at 06:50:50 PM BST 
//


package uk.ac.surrey.ee.iot.fiware.ngsi9.pojo;

import com.google.gson.annotations.SerializedName;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Restriction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Restriction">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="attributeExpression" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scope" type="{}OperationScopeList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Restriction")
public class Restriction {

    @XmlElement(required = true)
    protected String attributeExpression;
    @XmlElementWrapper(name="scope")
    @SerializedName("scopes")    
    protected List<OperationScope> operationScope;
//    protected OperationScopeList scope;

    /**
     * Gets the value of the attributeExpression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttributeExpression() {
        return attributeExpression;
    }

    /**
     * Sets the value of the attributeExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttributeExpression(String value) {
        this.attributeExpression = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link OperationScopeList }
     *     
     */
    public List<OperationScope> getOperationScope() {
        if (operationScope == null) {
            operationScope = new ArrayList<OperationScope>();
        }
        return this.operationScope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationScopeList }
     *     
     */
    

}
